Repository ashetta/okey-post, pull requests merged in 2022-05, with the labels that each got.

#1 feat: add fonts
  fonts/fonts.txt
  fonts/roboto-v29-latin-regular.woff
  fonts/roboto-v29-latin-regular.woff2
  scss/_fonts.scss
  scss/_general.scss
Labels: feature

#2 feat:add-container
  index.html
  scss/_general.scss
Labels: documentation

#3 fixed:containers
  index.html
  scss/_general.scss
  scss/blocks/_container.scss
Labels: good first issue

#4 feat:.vscode-file-added
  .vscode/settings.json
  img/images.txt
  img/logo.svg
  index.html
Labels: documentation

#10 so_many_things_added
  css/main.min.css
  css/main.min.css.map
  fonts/roboto-v29-latin-100.woff
  fonts/roboto-v29-latin-100.woff2
  fonts/roboto-v29-latin-300.woff
  fonts/roboto-v29-latin-300.woff2
  fonts/roboto-v29-latin-500.woff
  fonts/roboto-v29-latin-500.woff2
  fonts/roboto-v29-latin-700.woff
  fonts/roboto-v29-latin-700.woff2
  fonts/roboto-v29-latin-900.woff
  fonts/roboto-v29-latin-900.woff2
  img/buying-icon1.svg
  img/buying-icon2.svg
  img/intro1-bg.svg
  index.html
  scss/_fonts.scss
  scss/blocks/_all-blocks.scss
  scss/blocks/_support.scss
  scss/index_blocks/_all-blocks.scss
  scss/index_blocks/_header.scss
  scss/index_blocks/_intro.scss
  scss/index_blocks/_nav.scss
  scss/main.scss
  support.html
Labels: documentation, good first issue, feature
